config/routes.rb
CCWebApp::Application.routes.draw do

  # - Subscriptions -
  get "subscriptions/new"
  post "subscriptions/create_group"

  resources :orders

  devise_for :users, :controllers => {:sessions => "sessions", :confirmations => 'users', :passwords => "passwords"}
  resources :home

  match '/subscription' => 'subscribe#new', :as => 'subscription'

  resources :subscribe do
    get 'edit_billing_information'
    get 'providers'
    post 'providers'
    collection do
      get 'edit_billing_information'
      get 'billing_information'
      post 'create_billing_info'
      put 'update_billing_info'
      get 'checkout_confirmation'
    end
  end

  match 'reset_password/:id' => "admin/home#reset_password", :as => :reset_password
  match 'billing' => "activities#billing"
  namespace :admin do
    resources :home
  end

  resources :physician_groups, :path => 'groups' do
    post 'change_agency', :on => :collection
  end

  resources :physicians do
    get :photo
    get :change_billing_agency, :on => :collection
    post :upload
  end

  resources :providers


  resources :billing_agencies, :path => 'billing/agencies' do
    get 'profile'
    collection do
      get 'change_billing_agency'
      post 'search'
      post 'report'
      get 'history'
      post 'history'
      get 'physicians'
    end
  end

  resources :agency_employees, :path => 'agency/employees'

  resources :superbills do
    get :autocomplete_cpt_group_name, :on => :collection
    get :autocomplete_icd_description, :on => :collection
    get :autocomplete_cpt_code, :on => :collection
    get :add, :on => :collection
  end

  resources :referring_physicians, :path => 'referring/physicians'
  resources :facilities
  resources :activities do
    get :history, :on => :collection
  end
  resources :patients

  resources :capture_codes, :as => :encounters do
    get :autocomplete_icd_description, :on => :collection
    get :icd, :on => :collection
  end

  resources :notes

  resources :reports do
    get :autocomplete_physician_name, :on => :collection
    get :referral_volume,  :on => :collection
    post :referral_volume_report, :on => :collection
    get :list, :on => :collection
    post :generate, :on => :collection
  end

  match '/auth' => 'home#client_authentication', :as => 'http_auth', :method => :post
  match '/hm11' => 'home#index'
  match '/unsubscribe/:email' => 'home#unsubscribe'
  #match '/password' => 'home#forgot_password', :as => 'http_auth', :method => :post
  match '/pin' => 'home#set_pin', :as => 'http_auth', :method => :post

  match '/store_pin' => 'services#store_pin', :method => :post
  match '/forgot_pin' => 'services#forgot_pin', :method => :post
  match '/forgot_password' => 'services#forgot_password', :method => :post
  match '/superbill_pull' => 'services#superbill_pull', :method => :post

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'

  # - Searches -
  post '/search/npi' => 'searches#npi', :as => :npi_search

end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_filter :set_entity, :only => [:show, :billing_information, :create_billing_info, :edit, :update, :edit_billing_information, :update_billing_info]

  layout 'subscribe'

  def index
    @user = ProspectiveSubscriber.new
    @user.build_physician_group
    render :action => :new, :layout => 'home'
  end

  def create
    @user = ProspectiveSubscriber.new(params[:prospective_subscriber])
    @user.passed_step = 1
    respond_to do |format|
      if @user.save
        session[:prospective_subscriber_id] = @user.id
        LineItem.clear_and_create!(current_cart, @user)
        flash[:notice] = 'You have successfully subscribed for qliqCharge.'
        format.html { redirect_to billing_information_subscribe_index_path }
        format.xml { render :xml => @user, :status => :created, :location => @user }
        format.js {
          set_entity
          @billing_info = ProspectiveSubscriberBillingAddress.new
        }
      else
        @user.build_physician_group(params[:prospective_subscriber][:physician_group_attributes])

        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
        format.js {

        }
      end
    end
  end

  # GET /subscribe/1/edit
  # GET /subscribe/1/edit.xml
  def edit
    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
      format.json { render :json => @user.validations_to_json(:name) }
    end
  end

  # PUT /subscribe/1
  # PUT /subscribe/1.xml
  def update
    respond_to do |format|
      @user.attributes = params[:user]
      if @user.save
        LineItem.clear_and_create!(current_cart, @user)

        flash[:notice] = 'You have successfully updated qliqAccount.'
        if @physician_group.billing_info
          format.html { redirect_to subscribe_path(@physician_group) }
        else
          format.html { redirect_to billing_information_subscribe_index_path }
        end
        format.xml { render :xml => @user, :status => :created, :location => @user }
        format.js
      else
        raise @user.errors.inspect
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def show
    @billing_info = @physician_group.billing_info
    @order = @physician_group.prepare_order_object
#    unless cookies[:credit_card].nil?
#      @order = @physician_group.prepare_order_object(cookies[:credit_card])
#
#    else
#      redirect_to edit_billing_information_subscribe_index_path, :notice => 'No Credit Card information!'
#    end
    respond_to do |format|
      format.html
      format.xml { render :xml => @physician_group }
      format.json { render :json => @physician_group.validations_to_json(:name) }
    end
  end

  def billing_information
    @billing_info = ProspectiveSubscriberBillingAddress.new

    respond_to do |format|
      format.html
      format.xml { render :xml => @billing_info }
      format.json { render :json => @billing_info.validations_to_json(:name) }
      format.js
    end
  end

  def create_billing_info
    @billing_info = ProspectiveSubscriberBillingAddress.new(params[:prospective_subscriber_billing_address])
    @billing_info.prospective_subscriber = @user
    respond_to do |format|
      if @billing_info.save
        @user.update_attribute(:passed_step, 2)
        #cookies[:credit_card] = @billing_info.credit_card_hash
        flash[:notice] = 'Billing information successfully created.'
        format.html { redirect_to subscribe_path(@physician_group) }
        format.xml { render :xml => @billing_info, :status => :created, :location => @billing_info }
        format.js {
          @billing_info = @physician_group.billing_info
          @order = @physician_group.prepare_order_object
        }
      else
        format.html { render :action => "billing_information" }
        format.xml { render :xml => @billing_info.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def edit_billing_information
    @billing_info = @physician_group.billing_info
    respond_to do |format|
      format.html
      format.xml { render :xml => @billing_info }
      format.json { render :json => @billing_info.validations_to_json(:name) }
    end
  end

  def update_billing_info
    @billing_info = @physician_group.billing_info
    @billing_info.attributes = @user.respond_to?(:resource) ? params[:billing_info] : params[:prospective_subscriber_billing_address]

    #cookies[:credit_card] = @billing_info.credit_card_hash
    respond_to do |format|
      if @billing_info.save
        flash[:notice] = 'Billing information successfully updated.'
        format.html { redirect_to subscribe_path(@physician_group) }
        format.xml { render :xml => @billing_info, :status => :created, :location => @billing_info }
        format.js
      else
        format.html { render :action => "billing_information" }
        format.xml { render :xml => @billing_info.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def providers
  end

  def checkout_confirmation
    render :text => params.inspect
  end

  private
  def set_entity
    begin
      if session[:prospective_subscriber_id]
        @user = ProspectiveSubscriber.find(session[:prospective_subscriber_id])
        @physician_group = @user.physician_group
      else
        @user = current_user || User.find(session[:user_id])
        @physician_group = @user.resource
      end
    rescue
      redirect_to new_subscribe_path
      return
    end
  end
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
  def step1
    if @physician_group
  "<div class='create p_btm'><h3>Step 1:</h3><h3> #{link_to 'Create your qliqAccount', edit_subscribe_path(@physician_group), :remote => true} </h3> <strong> #{link_to "EDIT", edit_subscribe_path(@physician_group), :remote => true }</strong> </div>"
    else
  "<div class='create'><h3>Step 1:</h3><h3> Create your qliqAccount</h3> </div>"
    end
  end

  def step2
    if @physician_group and @physician_group.billing_info
  "<div class='create p_btm'><h3>Step 2:</h3><h3> #{link_to 'Billing Information', subscribe_edit_billing_information_path(@physician_group), :remote => true}</h3><strong> #{link_to "EDIT", subscribe_edit_billing_information_path(@physician_group), :remote => true } </strong></div>"
    else
  "<div class='create p_btm'><h3>Step 2:</h3><h3> Billing Information</h3> </div>"
      
    end
  end

  def step3
    if @physician_group and @physician_group.billing_info
  "<div class='create p_btm'><h3>Step 3:</h3><h3>#{link_to ' Review & Check Out',subscribe_path(@physician_group), :remote => true}</h3> <strong> #{link_to "SHOW", subscribe_path(@physician_group), :remote => true } </strong></div>"
    else
       "<div class='create p_btm'><h3>Step 3:</h3><h3> Review & Check Out</h3></div>"
    end
    end

  def step4
    if @physician_group
  "<div class='create p_btm'><h3>Step 4:</h3><h3> #{link_to 'Add Providers & Staff', edit_physician_group_path(@physician_group), :remote => true}</h3></div>"
    else
      "<div class='create p_btm'><h3>Step 4:</h3><h3>Add Providers & Staff</h3></div>"
    end
    end
end

app/views/subscribe/_billing_info_form.html.erb
<div class="chk"><%= p.check_box "is_account_info" %> Same as my qliqAccount Information</div>
<script type="text/javascript">

</script>

<div class="row1"> <%= p.text_field :first_name, :label => t('contact.first_name'), :div_class => "text" %> </div>
<div class="row1"> <%= p.text_field :last_name, :label => t('contact.last_name'), :div_class => "text" %> </div>
<div class="row1"> <%= p.text_field :title, :label => t('contact.name'), :div_class => "text", :required => "false" %>  </div>
<div class="row1"> <%= p.text_field :phone, :label => t('contact.phone'), :div_class => "text" %>  </div>
<div class="row1 pad_bottom"><%= p.text_field :email, :label => t('contact.subscribe_email'), :div_class => "text" %></div>
<div class="row1"> <%= p.text_field :company, :label => t('contact.company'), :div_class => "text" %>  </div>
<div class="row1"> <%= p.text_field :address1, :label => t('contact.address1'), :div_class => "text" %>  </div>
<div class="row1"> <%= p.text_field :address2, :label => t('contact.address2'), :div_class => "text", :required => "false" %>  </div>
<div class="row1"> <%= p.text_field :city, :label => t('contact.sub_city'), :div_class => "text" %></div>
<div class="row1"><%= p.select :state, STATES.collect { |s| [s.name, s.code] }, {:include_blank => "--select--"}, :label => t('contact.sub_state') %></div>
<div class="row1 pad_botom"> <%= p.text_field :zip, :label => t('contact.sub_zip'), :class => 'input_small width10', :div_class => "text" %>  </div>

<div class="row1">
  <input type="submit" value="Continue Step 3" name="commit" class="btn">
</div>


<script type="text/javascript">
    clientSideValidations.callbacks.element.fail = function(element, message, callback) {
        callback();
        $('#form_have_errors').show();

        element.parents('.text:first').addClass("invalid");
        var messageElement = jQuery('label.message[for="' + element.attr('id') + '"]');
        var isBlankFound = message.search(new RegExp(/blank/i));

        if (element.attr('id') == 'billing_info_email') {
            if (isBlankFound < 0)
                messageElement.text('Email ' + messageElement.text()).show();
        }

        if (element.attr('id') == 'billing_info_phone') {
            if (isBlankFound < 0)
                messageElement.show();
        }


    }

    clientSideValidations.callbacks.element.pass = function(element, callback) {
        element.parents('.text:first').removeClass("invalid");
        element.parent().find('.message').effect('fade', {}, 2000, callback);

        if ($('div.field_with_errors').length == 0)
            $('#form_have_errors').effect('fade', {}, 2000);

    }


    $(document).ready(function() {
        $('#billing_info_is_account_info').click(function() {
            if ($('#billing_info_is_account_info').is(':checked')) {
                $('#billing_info_first_name').val("<%= @physician_group.first_name%>").data('changed', true);
                $('#billing_info_last_name').val("<%= @physician_group.last_name%>").data('changed', true);
                $('#billing_info_title').val("<%= @physician_group.contact_title%>").data('changed', true);
                $('#billing_info_phone').val("<%= @physician_group.phone%>").data('changed', true);
                $('#billing_info_email').val("<%= @physician_group.user.email%>").data('changed', true);
                $('#billing_info_company').val("<%= @physician_group.name%>").data('changed', true);
                $('#billing_info_address1').val("<%= @physician_group.address%>").data('changed', true);
                $('#billing_info_address2').val("<%= @physician_group.address2%>").data('changed', true);
                $('#billing_info_city').val("<%= @physician_group.city%>").data('changed', true);
                $('#billing_info_state').val("<%= @physician_group.state%>").data('changed', true);
                $('#billing_info_zip').val("<%= @physician_group.zip%>").data('changed', true);
            }
            else {
                $('#billing_info_first_name').val("<%= @billing_info.first_name%>").data('changed', true);
                $('#billing_info_last_name').val("<%= @billing_info.last_name%>").data('changed', true);
                $('#billing_info_title').val("<%= @billing_info.title %>").data('changed', true);
                $('#billing_info_phone').val("<%= @billing_info.phone%>").data('changed', true);
                $('#billing_info_company').val("<%= @billing_info.company%>").data('changed', true);
                $('#billing_info_email').val("<%= @billing_info.email%>").data('changed', true);
                $('#billing_info_address1').val("<%= @billing_info.address1%>").data('changed', true);
                $('#billing_info_address2').val("<%= @billing_info.address2%>").data('changed', true);
                $('#billing_info_city').val("<%= @billing_info.city%>").data('changed', true);
                $('#billing_info_state').val("<%= @billing_info.state%>").data('changed', true);
                $('#billing_info_zip').val("<%= @billing_info.zip%>").data('changed', true);
            }

            var form = $('#new_billing_info');
            var settings = window[form.attr('id')];
            form.isValid(settings.validators);

        });

    })
</script>

app/views/subscribe/_form.html.erb
<fieldset>
  <%= f.fields_for :resource do |p| %>
      <div class="row1"> <%= p.text_field :first_name, :label => t('contact.first_name'), :div_class => "text" %> </div>
      <div class="row1"> <%= p.text_field :last_name, :label => t('contact.last_name'), :div_class => "text" %> </div>
      <div class="row1"> <%= p.text_field :contact_title, :label => t('contact.name'), :div_class => "text", :required => "false" %>  </div>
      <div class="row1"> <%= p.text_field :phone, :label => t('contact.phone'), :div_class => "text" %>  </div>
  <% end %>
  <div class="row1 pad_bottom"><%= f.text_field :email, :label => t('contact.subscribe_email'), :div_class => "text" %></div>
  <%= f.fields_for :resource do |p| %>
      <div class="row1"> <%= p.text_field :name, :label => t('contact.company'), :div_class => "text" %>  </div>
      <div class="row1"> <%= p.text_field :address, :label => t('contact.address1'), :div_class => "text" %>  </div>
      <div class="row1"> <%= p.text_field :address2, :label => t('contact.address2'), :div_class => "text", :required => "false" %>  </div>
      <div class="row1"> <%= p.text_field :city, :label => t('contact.sub_city'), :div_class => "text" %></div>
      <div class="row1"><%= p.select :state, STATES.collect { |s| [s.name, s.code] }, {:include_blank => "--select--"}, :label => t('contact.sub_state') %></div>
      <div class="row1"> <%= p.text_field :zip, :label => t('contact.sub_zip'), :div_class => "text width10" %>  </div>
      <div class="row1 pad_bottom"> <%= p.text_field :providers, :label => t('contact.providers'), :div_class => "text width11", :help => 'Number of Medical Providers in your Group' %>   </div>
  <% end %>
  <% if @user.new_record? %>
      <div class="password">
        <div class="row1"> <%= f.password_field :password, :value => "", :label => t('contact.password'), :div_class => "text width", :validate => {:presence => true, :confirmation => true} %>  </div>
        <div class="row1"> <%= f.password_field :password_confirmation, :label => t('contact.confirm_password'), :div_class => "text width" %> </div>
      </div>
      <div class="text width1 border_radius_5" id="password_format_note">
        <small class="font">Your password will be case sensitive and must contain at least 6 letters and/or numbers.
        </small>
      </div>

  <% end %>
  <div class="row1">
    <%= submit_tag "Continue Step 2", :class => "btn" %>
  </div>
</fieldset>

<script type="text/javascript">
    clientSideValidations.callbacks.element.fail = function(element, message, callback) {
        callback();
        $('#form_have_errors').show();

        element.parents('.text:first').addClass("invalid");
        var messageElement = jQuery('label.message[for="' + element.attr('id') + '"]');
        var isBlankFound = message.search(new RegExp(/blank/i));

        if (element.attr('id') == 'user_email') {
            if (isBlankFound < 0)
                messageElement.text('Email ' + messageElement.text()).show();
        }

        if (element.attr('id') == 'user_password') {
            $('#password_format_note').css('border', '2px solid #D1542B').children('small').css('color', 'red');
            if($('#user_password_confirmation').val().length == 0){
                element.parent().find('.message').hide();

            }
            else if (isBlankFound < 0) {
                messageElement.text('Password ' + messageElement.text()).show().css('left', '216px');
            }

        }

        if (element.attr('id') == 'user_resource_attributes_phone') {
            if (isBlankFound < 0)
                messageElement.show();
        }

        if (element.attr('id') == 'user_resource_attributes_zip') {
            if (isBlankFound < 0)
                messageElement.text( messageElement.text()).show().css('left', '89px').css('width', '100px');
        }

    };

    clientSideValidations.callbacks.element.pass = function(element, callback) {
        element.parents('.text:first').removeClass("invalid");
        element.parent().find('.message').effect('fade', {}, 2000, callback);

        if (element.attr('id') == 'user_password') {
            $('#password_format_note').css('border', 'none').children('small').css('color', '#6D6E71');
        }

        if($('div.field_with_errors').length == 0)
           $('#form_have_errors').effect('fade', {}, 2000);
    };



</script>

app/views/subscribe/_payment_form.html.erb
<div class="bottom_section">
  <div class="bottom_left">
    <div class="secure">
      <h5>Secure credit card verification</h5>
      <a href="#"><img src="/images/lock.png" alt=""></a>

      <p>This is a secure, 128-bit SSL encrypted card verification. </p>

      <p>Your card will not be charged until the end of your 30-day trial period (June 8, 2011).</p>
      <span class="clear"></span></div>
    <div class="listing">

      <ul>
        <li>
          <div class="credit_card">
            <p class="bold"> Credit card type</p>

            <p>Please select your credit card type.</p>

            <div class="row3 bg_none">
              <%= p.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], :include_blank => 'Select card type' %>

            </div>
          </div>

        </li>
        <li>
          <div class="credit_card">
            <p class="bold"> Credit card number</p>

            <p>Please enter the 16-digit number on the front of your credit card.</p>

            <div class="row3 text">
              <%=p.text_field :card_number%>
            </div>
          </div>

        </li>

        <li>
          <div class="credit_card">
            <p class="bold"> Expiration date</p>

            <p>The date your credit card expires, found on the front of your credit card.</p>

            <div class="row3 bg_none">
               <%= p.select :card_expires_on_month, (1..12).collect{|m| m <= 9 ? "0#{m}" : m}, :prompt => 'Month'%>
              <label>/</label>
              <%= p.select :card_expires_on_year, Date.today.year.to_i..Date.today.year.to_i+10, :prompt => 'Year'%>
            </div>
          </div>
        </li>
        <li>
          <div class="credit_card length">
            <p class="bold"> Security code
              <small>(or “CVC” or “CVV”)</small>
            </p>
            <p>The last 3 digits on the back of your credit card.</p>

            <div class="row3 inpt text">
              <%= p.text_field :card_verification%>
            </div>
          </div>
          <div class="card"><a href="#"><img src="/images/card.gif" alt=""></a></div>
        </li>
      </ul>
    </div>
  </div>
  <div class="bottom_right">
    <div class="security"><span>Sercurity</span> <span>Badge</span></div>
  </div>
</div>
<div class="content_step1">
  <div class="row1">
    <%= submit_tag "Continue Step 3", :class => "btn" %>
  </div>
</div>

app/views/subscribe/billing_information.html.erb
<fieldset>
  <div class="left_container">
    <div class="step1">
      <div class="mid_curve1">
        <div class="top_curve4">
          <div class="bottom_curve4">
            <%= form_for(@billing_info, :url => create_billing_info_subscribe_index_path, :method => :post, :remote => true, :builder => FormBuilder, :validate => true) do |p| %>
                <div class="content_step1">
                  <h2><a href="#">Subscribe to qliqCharge</a></h2>


                  <%= raw step1 %>
                  <%#= raw step2 %>
                  <div class='create p_btm'>
                    <h3>Step 2:</h3>

                    <h3><%= link_to 'Billing Information' %></h3>


                    <br/>
                    <%= render :partial => "tmp_billing_info_form", :locals => {:p => p} %>
                  </div>
                </div>


                <%#= render :partial => 'payment_form', :locals => {:p => p} %>
            <% end %>

            <div class="content_step1">
              <%= raw step3 %>
              <%= raw step4 %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="right_container pad_top3">
    <h4>Take a month to see how it all works!</h4>

    <p>Ut dapibus convallis felis sit amet auctor. Nullam condimentum enim et lectus blandit faucibus. Quisque eget
      tortor justo. Phasellus arcu risus, porttitor nec tincidunt nec, ultricies sit amet felis.</p>
  </div>
</fieldset>

app/views/subscribe/create.js.erb
<% if @user.errors.any? -%>
$("#flash_notice").hide(300);
$("#form_have_errors").html("<%= escape_javascript(error_messages_for(@user))%>");
$("#form_have_errors").show(300);
<% else -%>
<%flash.discard%>
$("#form_have_errors").hide(300);
$("#ajax_response_container").html("<%= escape_javascript( render :template => "subscribe/billing_information") %>");
var form = $('#new_prospective_subscriber_billing_address');
form.validate();
<% end -%>

app/views/subscribe/create_billing_info.js.erb
<% if @billing_info.errors.any? -%>
$("#flash_notice").hide(300);
$("#form_have_errors").html("<%= escape_javascript(error_messages_for(@billing_info))%>");
$("#form_have_errors").show(300);
<% else -%>
<%flash.discard%>
$("#form_have_errors").hide(300);
$("#ajax_response_container").html("<%= escape_javascript( render(:template => "subscribe/show") ) %>");
var form = $('#order_form');
form.validate();
<% end -%>

app/views/subscribe/edit.html.erb
<fieldset>
  <div class="left_container">
    <div class="step1">
      <div class="mid_curve1">
        <div class="top_curve1">
          <div class="bottom_curve1">
            <div class="content_step1">
              <h2><a href="#">Subscribe to qliqCharge</a></h2>

              <div class='create'>
                <h3>Step 1:</h3>

                <h3><%= link_to 'Create your qliqAccount' %></h3>
                <%= raw "<h3 class='color' id='form_have_errors' style='display:#{@user.errors.blank? ? 'none' : 'block'}'>Please correct or fill out highlighted fields</h3>" %>
              </div>
              <%= form_for(@user, :url => subscribe_path(@physician_group.id), :remote => true, :method => :put, :builder => FormBuilder, :validate => true) do |f| %>
                  <%= render :partial => @user.respond_to?(:resource) ? 'form' : 'tmp_form', :locals => {:f => f} %>
              <% end %>

              <%= raw step2 %>
              <%= raw step3 %>
              <%= raw step4 %>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="right_container">
      <h4>Take a month to see how it all works!</h4>

      <p>Ut dapibus convallis felis sit amet auctor. Nullam condimentum enim et lectus blandit faucibus. Quisque eget
        tortor justo. Phasellus arcu risus, porttitor nec tincidunt nec, ultricies sit amet felis.</p>
    </div>
</fieldset>

app/views/subscribe/edit.js.erb
<% if @user.errors.any? -%>
$("#flash_notice").hide(300);
$("#form_have_errors").html("<%= escape_javascript(error_messages_for(@user))%>");
$("#form_have_errors").show(300);
<% else -%>
<%flash.discard%>
$("#form_have_errors").hide(300);
$("#ajax_response_container").html("<%= escape_javascript( render(:template => "edit") ) %>");
var form = $('#new_prospective_subscriber_billing_address');
form.validate();
<% end -%>

app/views/subscribe/edit_billing_information.html.erb
<fieldset>
  <div class="left_container">
    <div class="step1">
      <div class="mid_curve1">
        <div class="top_curve4">
          <div class="bottom_curve4">
            <%= form_for(@billing_info, :url => update_billing_info_subscribe_index_path, :method => :post, :builder => FormBuilder, :validate => true) do |p| %>

                <div class="content_step1">
                  <h2><a href="#">Subscribe to qliqCharge</a></h2>


                  <%= raw step1 %>
                  <%# raw step2 %>
                  <div class='create p_btm'>
                    <h3>Step 2:</h3>

                    <h3><%= link_to 'Billing Information' %></h3>
                    <%= raw "<h3 class='color' id='form_have_errors' style='display:#{@billing_info.errors.blank? ? 'none' : 'block'}'>Please correct or fill out highlighted fields</h3>" %>

                    <br/>
                    <%= render :partial => @user.respond_to?(:resource) ? 'billing_info_form' : 'tmp_billing_info_form', :locals => {:p => p} %>
                    <br/>

                  </div>

                </div>
                <%#= render :partial => 'payment_form', :locals => {:p => p} %>
            <% end %>

            <div class="content_step1">
              <%= raw step3 %>
              <%= raw step4 %>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="right_container pad_top3">
      <h4>Take a month to see how it all works!</h4>

      <p>Ut dapibus convallis felis sit amet auctor. Nullam condimentum enim et lectus blandit faucibus. Quisque eget
        tortor justo. Phasellus arcu risus, porttitor nec tincidunt nec, ultricies sit amet felis.</p>
    </div>

</fieldset>

app/views/subscribe/new.html.erb
<% content_for :head do -%>
  <%= stylesheet_link_tag 'home_style', 'av_hack', 'client_side_validation' %>
  <%= javascript_include_tag 'rails.validations', 'rails.validations.custom' %>
<% end %>
<div id="ajax_response_container">
  <fieldset>
    <div class="left_container">
      <div class="step1">
        <div class="mid_curve1">
          <div class="top_curve1">
            <div class="bottom_curve1">
              <div class="content_step1">
                <h2>
                  <a href="#">Subscribe to qliqCharge</a>
                  <span style='margin-left:15px; font-size:12px; color:#D2542A'><%= flash[:error] %></span>
                </h2>
                <div class='create'>
                  <h3>Step 1:</h3>
                  <h3><%= link_to 'Create your qliqAccount' %></h3>
                  <%= raw "<h3 class='color' id='form_have_errors' style='display:#{@user.errors.blank? ? 'none' : 'block'}'>Please correct or fill out highlighted fields</h3>" %>
                </div>
                <%= form_for(@user, :url => subscribe_index_path, :method => :post, :remote => true, :builder => FormBuilder, :validate => true) do |f| %>
                  <%= render :partial => 'tmp_form', :locals => {:f => f} %>
                <% end %>
                <%= raw step2 %>
                <%= raw step3 %>
                <%= raw step4 %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="right_container">
      <h4>Take a month to see how it all works!</h4>
      <p>Ut dapibus convallis felis sit amet auctor. Nullam condimentum enim et lectus blandit faucibus. Quisque eget
      tortor justo. Phasellus arcu risus, porttitor nec tincidunt nec, ultricies sit amet felis.</p>
    </div>
  </fieldset>
</div>