config/routes.rb
CCWebApp::Application.routes.draw do

  # - Subscriptions -
  get "subscriptions/new"
  post "subscriptions/create_group"

  resources :orders

  devise_for :users, :controllers => {:sessions => "sessions", :confirmations => 'users', :passwords => "passwords"}
  resources :home

  match '/subscription' => 'subscribe#new', :as => 'subscription'

  resources :subscribe do
    get 'edit_billing_information'
    get 'providers'
    post 'providers'
    collection do
      get 'edit_billing_information'
      get 'billing_information'
      post 'create_billing_info'
      put 'update_billing_info'
      get 'checkout_confirmation'
    end
  end

  match 'reset_password/:id' => "admin/home#reset_password", :as => :reset_password
  match 'billing' => "activities#billing"
  namespace :admin do
    resources :home
  end

  resources :physician_groups, :path => 'groups' do
    post 'change_agency', :on => :collection
  end

  resources :physicians do
    get :photo
    get :change_billing_agency, :on => :collection
    post :upload
  end

  resources :providers


  resources :billing_agencies, :path => 'billing/agencies' do
    get 'profile'
    collection do
      get 'change_billing_agency'
      post 'search'
      post 'report'
      get 'history'
      post 'history'
      get 'physicians'
    end
  end

  resources :agency_employees, :path => 'agency/employees'

  resources :superbills do
    get :autocomplete_cpt_group_name, :on => :collection
    get :autocomplete_icd_description, :on => :collection
    get :autocomplete_cpt_code, :on => :collection
    get :add, :on => :collection
  end

  resources :referring_physicians, :path => 'referring/physicians'
  resources :facilities
  resources :activities do
    get :history, :on => :collection
  end
  resources :patients

  resources :capture_codes, :as => :encounters do
    get :autocomplete_icd_description, :on => :collection
    get :icd, :on => :collection
  end

  resources :notes

  resources :reports do
    get :autocomplete_physician_name, :on => :collection
    get :referral_volume,  :on => :collection
    post :referral_volume_report, :on => :collection
    get :list, :on => :collection
    post :generate, :on => :collection
  end

  match '/auth' => 'home#client_authentication', :as => 'http_auth', :method => :post
  match '/hm11' => 'home#index'
  match '/unsubscribe/:email' => 'home#unsubscribe'
  #match '/password' => 'home#forgot_password', :as => 'http_auth', :method => :post
  match '/pin' => 'home#set_pin', :as => 'http_auth', :method => :post

  match '/store_pin' => 'services#store_pin', :method => :post
  match '/forgot_pin' => 'services#forgot_pin', :method => :post
  match '/forgot_password' => 'services#forgot_password', :method => :post
  match '/superbill_pull' => 'services#superbill_pull', :method => :post

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'

  # - Searches -
  post '/search/npi' => 'searches#npi', :as => :npi_search

end

app/models/billing_agency.rb
class BillingAgency < ActiveRecord::Base
  set_table_name 'billing_agency'
  has_many :agency_employees, :class_name => 'AgencyEmployee', :dependent => :destroy
  has_many :billing_prefs, :class_name => 'BillingPref'
  has_many :physician_groups, :through => :billing_prefs
  has_many :superbills, :class_name => 'Superbill', :dependent => :destroy
  has_many :agency_users, :through => :agency_employees, :source => :user

  has_one :user, :as => :resource, :dependent => :destroy
  accepts_nested_attributes_for :user, :allow_destroy => true 
  accepts_nested_attributes_for :billing_prefs, :allow_destroy => true 
 
  validates :first_name, :presence => true#, :uniqueness => true
  validates :last_name , :presence => true#, :uniqueness => true
 # validates :phone, :presence => true, :format => { :with =>  /^(\d{3}-){2}\d{4}$/, :message => 'Invalid phone number'}
 # validates_numericality_of :zip, :greater_than_or_equal_to => 0 , :less_than_or_equal_to => 999999,  :allow_blank => true, :only_integer => true, :message => 'Invalid value for zip'
 # validate :validate_zip
  def validate_zip
    unless self.zip.empty?
      validates_length_of :zip, :minimum => 5, :maximum => 10
    end
  end

 # validates_format_of :fax, :with =>  /^(\d{3}-){2}\d{4}$/, :allow_blank => true, :message => 'Invalid fax number'
  #
end

app/controllers/billing_agencies_controller.rb
require 'pdf_report'
class BillingAgenciesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_filter :get_billing_agency, :except => [:index, :new, :create, :destroy, :change_billing_agency, :edit, :update]
  layout 'billing_agency'

  # GET /billing_agencies
  # GET /billing_agencies.xml
  def index
    @billing_agencies = BillingAgency.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @billing_agencies }
    end
  end

  # GET /billing_agencies/1
  # GET /billing_agencies/1.xml
  def show
    @billing_agency = BillingAgency.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @billing_agency }
    end
  end

  # GET /billing_agencies/new
  # GET /billing_agencies/new.xml
  def new
    @billing_agency = BillingAgency.new
    @billing_agency.build_user
    load_defaults
    respond_to do |format|
      format.html { render :layout => false } 
    end
  end

  # GET /billing_agencies/1/edit
  def edit
    @billing_agency = BillingAgency.find(params[:id])
    load_defaults
    respond_to do |format|
      format.html { render :layout => false   } 
    end
  end

  # POST /billing_agencies
  # POST /billing_agencies.xml
  def create
    @billing_agency = BillingAgency.new(params[:billing_agency])
    @billing_agency.user.roles = ROLES[BILLING_ADMIN].to_a
    load_defaults
    respond_to do |format|
      if @billing_agency.save
        flash[:notice] = 'Billing agency was successfully created.'
        format.html { redirect_to(@billing_agency) }
        format.js {
              render :js => "window.location='#{billing_agencies_path}'"
        }
      else
        format.html { render :action => "new" }
        format.js {
          render :partial => 'new'
        }
      end
    end
  end

  # PUT /billing_agencies/1
  # PUT /billing_agencies/1.xml
  def update
    load_defaults
    @billing_agency = BillingAgency.find(params[:id])
    @billing_agency.attributes = params[:billing_agency]
    flag = @billing_agency.user.email_changed? ? true : false

    respond_to do |format|
      if @billing_agency.save
        @billing_agency.user.reset_email if flag 
        flash[:notice] = 'Billing agency was successfully updated.'
        format.html { redirect_to(@request_source) }
        format.xml  { head :ok }
        format.js {
              render :js => "window.location='#{@request_source}'"
        }
      else
        load_defaults
        format.html { render :action => "edit" }
        format.xml  { render :xml => @billing_agency.errors, :status => :unprocessable_entity }
        format.js {
          render :partial => 'new'
        }
      end
    end
  end

  # DELETE /billing_agencies/1
  # DELETE /billing_agencies/1.xml
  def destroy
    @billing_agency = BillingAgency.find(params[:id])
    @billing_agency.destroy

    respond_to do |format|
      format.html { redirect_to(billing_agencies_url) }
      format.xml  { head :ok }
    end
  end

  def change_billing_agency
    @billing_agency = BillingAgency.find(params[:billing_agency_id])
    respond_to do |format|
    #   format.html {render :action => "show" }
       format.js {
         render :partial => 'show'
       }
    end
  end
 
  def profile
    load_report_defaults
    @billing_patient = BillingPatient.new
  end

  def search
    load_report_defaults
    @billing_patient = BillingPatient.new(params[:billing_patient])
    load_patients(@billing_patient) 
    flash[:notice] =  "No data available" if @patients.empty?
    respond_to do |format|
      format.html { render :action => :profile   } 
    end
  end

  def report
    load_report_defaults
    @billing_patient = BillingPatient.new(params[:billing_patient])
    load_patients(@billing_patient) 
    if @patients.empty?
      flash[:notice] =  "No data available"
      respond_to do |format|
        format.html { render :action => :profile   } 
      end
    elsif params[:commit] == "Export Selected to PDF"   
      if !params[:select_all]
        patients_list = Patient.find(params[:patients]).collect(&:id)            
      else
        patients_list = @patients.collect(&:id)
      end
      directory = RAILS_ROOT + "/public/system/reports"
      Dir.mkdir( directory ) unless File.exists?( directory )
      filename= PdfReport.generate_billing_agency_report(@patients, @billing_agency.id, @billing_agency.name, patients_list)
      send_file RAILS_ROOT + "/public/system/reports/#{filename}"
      save_report_information(filename)
      generate_report(params) if params[:patients]
    elsif params[:print_report] == "1"
      @patients = Patient.find(params[:patients])
      respond_to do |format|
        format.html { render :layout => false   } 
      end
    else
      respond_to do |format|
        format.html { render :action => :profile   } 
      end
    end
  end

  def physicians
    if params[:group_id].blank? 
      @physicians = Physician.by_billing_agency(@billing_agency.id)
    else
      group = PhysicianGroup.find(params[:group_id])
      @physicians = Physician.physicians_billing_agency(@billing_agency.id, group.physicians.collect(&:id))
    end
    respond_to do |format|
      format.js { render :partial =>  'physicians' } 
    end
  end

  def history
    load_report_defaults
    @billing_patient = params[:billing_patient].blank? ? BillingPatient.new : BillingPatient.new(params[:billing_patient])
    get_billing_history
  end

  def load_defaults
    @request_source = request.env["HTTP_REFERER"]
  end

  def load_report_defaults
    @groups = PhysicianGroup.by_billing_agency(@billing_agency.id)
    @physicians = []#Physician.by_billing_agency(@billing_agency.id)
    @patients = []
  end

  def load_patients(billing_patient)
    if billing_patient.group.blank? && billing_patient.physician.blank?
      @patients = Patient.joins(:encounters, :physician).where("encounter.processed_date is NULL and (physician.id in (?) or physician.group_id in (?))", @groups.collect(&:id), @physicians.collect(&:id))
    elsif !billing_patient.group.blank? && billing_patient.physician.blank?
      @patients = Patient.joins(:encounters, :physician).where("encounter.processed_date is NULL and physician.group_id = ?", billing_patient.group)
    elsif billing_patient.group.blank? && !billing_patient.physician.blank?
      @patients = Patient.joins(:encounters, :physician).where("encounter.processed_date is NULL and physician.id = ?", billing_patient.physician)
    else
      @patients = Patient.joins(:encounters, :physician).where("encounter.processed_date is NULL and physician.id = ? and physician.group_id = ?", billing_patient.physician, billing_patient.group)
    end
    @patients = @patients.uniq
  end

  def generate_report(params)
    params[:patients].each do |patient_id|
      Encounter.update_all ["processed_date = ?", Date.today], ["id in (?)", params[:encounters][patient_id.to_s]]
    end
  end

  def save_report_information(file)
    report = BillingReport.new
    report.processed_date = Date.today
    report.user = current_user
    report.group = @billing_patient.group.blank? ? "All" : PhysicianGroup.find(@billing_patient.group).name
    report.physician = @billing_patient.physician.blank? ? "All" : Physician.find(@billing_patient.physician).name
    report.report_path = file
    report.save
  end

  def get_billing_agency
    if current_user.roles.include?(ROLES[BILLING_ADMIN])
      @billing_agency = current_user.resource
    else
      @billing_agency = current_user.resource.billing_agency
    end
  end

  def get_billing_history
    billing_users = []
    billing_users << @billing_agency.user.id
    billing_users << @billing_agency.agency_users.collect(&:id)
    billing_users = billing_users.flatten
    if @billing_patient.group.nil? && @billing_patient.physician.nil?
      @history = BillingReport.where("user_id in (?)", billing_users)
    elsif !@billing_patient.group.nil? && @billing_patient.physician.nil?
      @history = BillingReport.where("user_id in (?) and \"group\" = ?", billing_users, PhysicianGroup.find(@billing_patient.group).name)
    elsif @billing_patient.group.nil? && !@billing_patient.physician.nil?
      @history = BillingReport.where("user_id in (?) and physician = ?", billing_users, Physician.find(@billing_patient.physician).name)
    else
      @history = BillingReport.where("user_id in (?) and \"group\" = ? and physician = ?", billing_users, PhysicianGroup.find(@billing_patient.group).name, Physician.find(@billing_patient.physician).name)
    end
  end
end

app/views/billing_agencies/_form.html.erb
<script type="text/javascript">
  $(function() {
      initialize_form();

      var v = $("#frmAdmin").jcheck({notifiers: ["custom_errors"], live_notifiers: ["custom_errors"], field_prefix: "billing_agency"});
      v.validates("first_name", "last_name", "user_attributes[email]",{presence: true});
      v.validates_format_of("user_attributes[email]", {"with": "email"});
      $('#frmAdmin').submit(function(e) {
        e.preventDefault();
        return v.is_valid();
        });
  });
</script>
<%= form_for(@billing_agency, :html => { :remote => true, :id => "frmAdmin"}, :builder => CCFormBuilder) do |f| %>
  <%= f.text_field :first_name, :label => t('.name') + t('mandatory') %>  
  <%= f.text_field :last_name, :label => t('.name') + t('mandatory') %>  
  <%= f.text_field :address, :label => t('contact.address')  %>  
  <%= label_tag t('contact.location')  %><br/>  
  <%= text_field :billing_agency, :city, :class => "width1" %>  
  <%=select :billing_agency, :state, STATES.collect{|s| [s.name, s.code]}, {:include_blank => "-select-"}, :class => "width2"%>  
  <%= text_field :billing_agency, :zip, :class => "width3" %>  
  <%= raw "<div class='errMsg'>#{@billing_agency.errors[:zip].first}</div>" unless @billing_agency.errors[:zip].empty?  %> 
  <%= f.text_field :phone, :label => t('contact.phone') + t('mandatory') %>  
  <%= f.text_field :fax, :label => t('contact.fax')  %>  
  <%= f.fields_for :user do |u|  %>  
    <%= u.text_field :email, :label => t('contact.email') + t('mandatory') %>  
  <% end %>
  <div class="butons">
    <%= f.submit "Add", :class => :backgrnd %>
    <%= link_to 'Back', @request_source, :class => "backgrnd_lnk margin_rte" %>
    <%= image_tag "/images/spinner.gif", :id => "spinner", :style => "display:none;"  %>  
  </div>
<% end %>
<%= render :partial => "/physician_groups/events"  %>  

app/views/billing_agencies/_new.js.erb
$("#frmGroup").html('<%= escape_javascript(render :partial => "form") %>');

app/views/billing_agencies/_profile.html.erb
<h3 style="float:right;"></h3>
<div align="centre"  id="main" style="float: left;margin-left: 100px;">
  <table  cellpadding="4" cellspacing="4">
    <tr class="light_blue">
      <td> Name </td>
      <td><%= @billing_agency.name  %></td>
    </tr>
    <tr class="light_blue">
      <td> Email </td>
      <td><%= @billing_agency.user.try(:email)  %></td>
    </tr>
    <tr class="light_blue">
      <td> Phone </td>
      <td><%= @billing_agency.phone  %></td>
    </tr>
  </table>

  <%= form_for("physician_group" , :as => 'post', :url => change_agency_physician_groups_path) do |f| %>
    <%= f.hidden_field 'billing_agency_id',  :value => @billing_agency.id %>
    <div class="butons">
      <%= f.submit "Change", :class => :backgrnd  %>
    </div> 
  <% end %> 
</div>

app/views/billing_agencies/history.html.erb
<script type="text/javascript">
  $(document).ready(function () {
      $('#select_all').click(function() {
        $(':checkbox').attr('checked', this.checked);
      });

      $('#billing_patient_group').change(function() {
        var group_id = $('#billing_patient_group').val();
        $.ajax({
            url : '/billing/agencies/physicians',
            type : 'GET',
            data : 'group_id=' + group_id
        });
      });
  });
</script>
<%= render :partial => "/layouts/agency_left_menu"  %>
<div class="interface_right_section">
  <h1>History</h1>
  <div style="margin-bottom:10px;float:left;">
    <%= form_for(@billing_patient, :url => history_billing_agencies_path, :html => {:style => "width:660px;padding:0", :method => :post}) do |f|  %>  
      <fieldset>
        <div class="fields" style="width:auto;margin-top: 5px;">
          <%= label_tag "Group"  %>  
          <%= f.select :group, @groups.collect{|a| [a.name, a.id]}, {:include_blank => "All"}, :style => "width:100px;"  %>  
        </div>  
        <div id="physicians">
          <div class="fields" style="width:auto;margin-left:10px;margin-top: 5px;">
            <%= label_tag "Physician"  %>  
            <%= f.select :physician, @physicians.collect{|a| [a.name, a.id]}, {:include_blank => "All"}, :style => "width:100px;"  %>  
          </div>  
        </div>  
        <div class="fields" style="width:auto;margin-left:20px;">
          <div class="butons" style="padding:0">
            <%= submit_tag "Search", :class => :backgrnd  %>  
          </div>  
        </div>  
      </fieldset> 
    <% end %>  
  </div>  
  <div style="width:100%;float:left;" id="main">
    <table cellpadding="0" cellspacing="0" style="margin: 10px 0 10px 30px; width: 550px;">
      <tr class="interface_heading">
        <td class="col31_top none">Date</td>
        <td class="none">Group</td>
        <td class="none">Physician</td>
        <td class="none">User</td>
        <td class="none">File Name</td>
      </tr>
      <% @history.each do |history| %>  
        <tr class="light_blue">
          <td class="col31"><%= history.processed_date  %></td>   
          <td><%= history.group  %></td>   
          <td><%= history.physician  %></td>   
          <td><%= history.user.resource.name  %></td>   
          <td><%= link_to history.report_path, "/system/reports/" + history.report_path, :target => '_blank'  %></td>   
        </tr> 
      <% end %>  
    </table>
  </div>
</div>

app/views/billing_agencies/index.html.erb
<%= render :partial => "/admin/home/left_menu"  %>  
<div class="interface_right_section">
  <h3>Billing Agencies</h3>
  <div class="add"><%= link_to "Add Billing Agency", new_billing_agency_path, :rel => :facebox  %></div>
  <table cellpadding="0" cellspacing="0">
    <tr class="interface_heading">
      <td class="col31_top none">NAME</td>
      <td class="none">EMAIL</td>
      <td class="none">PHONE</td>
      <td class="none">&nbsp;</td>
    </tr>
    <% @billing_agencies.each do |billing_agency| %>
      <tr class="light_blue">
        <td class="col31"><%= billing_agency.name  %></td> 
        <td><%= billing_agency.user.try(:email)  %></td> 
        <td><%= billing_agency.phone  %></td>   
        <td class="edit-link border_right"><%= link_to 'Edit', edit_billing_agency_path(billing_agency), :rel => :facebox %> |
        <%= link_to 'Delete', billing_agency, :method => :delete, :confirm => "Are you sure?" %> |
        <%= link_to 'Reset password', reset_password_path(billing_agency.user), :rel => :facebox %></td> 
      </tr>
    <% end %>  
  </table>
</div>

app/views/billing_agencies/profile.html.erb
<script type="text/javascript">
  $(document).ready(function () {
      $('#select_all').click(function() {
        $(':checkbox').attr('checked', this.checked);
      });

      $('#billing_patient_group').change(function() {
        var group_id = $('#billing_patient_group').val();
        $.ajax({
            url : '/billing/agencies/physicians',
            type : 'GET',
            data : 'group_id=' + group_id
        });
      });
  });
  function is_patient_selected(id)
  {
    var patients = $(":checkbox[name='patients[]']").filter(':checked');
    if(patients.length == 0)
    {
      alert("Please select atleast one patient");
      return false;
    }
    if(id == 1)
    {
      /*window.print();
      $('#main').printElement({pageTitle:'Ardensys Billing Agency Report'});*/
      $('#print_report').val(1);
    }
    return true; 
  }
</script>
<%= render :partial => "/layouts/agency_left_menu"  %>
<div class="interface_right_section">
  <h1>Inbox</h1>
  <div style="margin-bottom:10px;float:left;">
    <%= form_for(@billing_patient, :url => search_billing_agencies_path, :html => {:style => "width:660px;padding:0"}) do |f|  %>  
      <fieldset>
        <div class="fields" style="width:auto;margin-top: 5px;">
          <%= label_tag "Group"  %>  
          <%= f.select :group, @groups.collect{|a| [a.name, a.id]}, {:include_blank => "All"}, :style => "width:100px;"  %>  
        </div>  
        <div id="physicians">
          <div class="fields" style="width:auto;margin-left:10px;margin-top: 5px;">
            <%= label_tag "Physician"  %>  
            <%= f.select :physician, @physicians.collect{|a| [a.name, a.id]}, {:include_blank => "All"}, :style => "width:100px;"  %>  
          </div>  
        </div>  
        <div class="fields" style="width:auto;margin-left:20px;">
          <div class="butons" style="padding:0">
            <%= submit_tag "Generate Report", :class => :backgrnd  %>  
          </div>  
        </div>  
      </fieldset> 
    <% end %>  
  </div>  
  <hr>
  <%= form_tag(report_billing_agencies_path, :style => "width:660px;padding:0") do   %>  
    <%= hidden_field_tag "billing_patient[group]", @billing_patient.group  %>  
    <%= hidden_field_tag "billing_patient[physician]", @billing_patient.physician  %>  
    <div>
      <div style="margin-top:10px;margin-bottom:10px;float:left;">
        <fieldset>
          <div class="fields" style="width:auto;margin-top: 5px;">
            <%= check_box_tag :select_all, '1' ,false, :style => "width:20px;"  %>  
            <span>Select All</span>
          </div>  
          <div class="fields" style="width:auto;margin-left:20px;">
            <div class="butons" style="padding:0">
              <%= submit_tag "Export Selected to PDF", :class => :backgrnd, :onclick => "return is_patient_selected(0);"  %>  
            </div>  
          </div>  
          <div class="fields" style="width:auto;margin-left:20px;">
            <div class="butons" style="padding:0">
              <%= hidden_field_tag 'print_report', ''  %>
              <%= submit_tag "Print Selected", :class => :backgrnd, :onclick => "return is_patient_selected(1);"  %>  
            </div>  
          </div>  
        </fieldset> 
      </div>  
      <hr>
    </div>  
    <div style="width:100%;float:left;" id="main">
      <% @patients.each do |patient| %>  
        <% encounters = patient.encounters.unbilled.uniq %>  
        <% unless encounters.empty? %>  
          <div id="print_for_<%= patient.id %>">
            <div style="float:left;">
              <%= check_box_tag "patients[]", patient.id ,false, :style => "width:20px;"  %>  
              <%= get_patient_name(patient)  %>  
              <b style="margin-left:20px;margin-right:10px;">DOB :</b><%= patient.date_of_birth.strftime("%Y/%m/%d")  %>  
            </div>  
            <table cellpadding="0" cellspacing="0" style="margin: 10px 0 10px 30px; width: 550px;">
              <tr class="interface_heading">
                <td class="col31_top none">DOS</td>
                <td class="none">ICD9(p)</td>
                <td class="none">ICD9</td>
                <td class="none">ICD9</td>
                <td class="none">ICD9</td>
                <td class="none">CPT</td>
              </tr>
              <% encounters.each do |encounter| %>  
                <%= hidden_field_tag "encounters[#{patient.id}][]", encounter.id  %>  
                <tr class="light_blue">
                  <td class="col31"><%= encounter.date_of_service.strftime('%m/%d')  %></td>
                  <% unless encounter.encounter_icds.primary.empty?  %> 
                    <td class="col31" style="text-align:center;"><%= encounter.encounter_icds.primary.first.icd.code %></td>   
                  <% else  %>
                    <td class="col31" style="text-align:center;">&nbsp;</td> 
                  <% end %>  
                  <% general_icds = encounter.encounter_icds.general %> 
                  <% unless general_icds[0].nil?  %> 
                    <td class="col31" style="text-align:center;"><%= general_icds[0].icd.code %></td> 
                  <% else  %>
                    <td class="col31" style="text-align:center;">&nbsp;</td> 
                  <% end %>  
                  <% unless general_icds[1].nil?  %> 
                    <td class="col31" style="text-align:center;"><%= general_icds[1].icd.code %></td>   
                  <% else %>
                    <td class="col31" style="text-align:center;">&nbsp;</td> 
                  <% end %>  
                  <% unless general_icds[2].nil?  %> 
                    <td class="col31" style="text-align:center;"><%= general_icds[2].icd.code %></td>   
                  <% else %>
                    <td class="col31" style="text-align:center;">&nbsp;</td> 
                  <% end %>  
                  <td class="col31" style="text-align:center;"><%= get_cpts_codes(encounter.cpts.collect(&:cpt_id))  %></td>   
                </tr> 
              <% end %>  
            </table>
            <hr>
          </div>  
        <% end %>  
      <% end %>  
    </div>  
  <% end %>  
</div>

app/views/billing_agencies/report.html.erb
<%= stylesheet_link_tag 'style', :media => 'all' %>
<style type="text/css">
  body {
  background: none;
  }
</style>
<div class="interface_right_section" style="float:left;border:0;">
  <h1 style="margin-bottom: 30px;text-align: center;"><%= @billing_agency.name  %> Report</h1> 
  <div style="width:100%;float:left;" id="main">
    <% @patients.each do |patient| %>  
      <% encounters = patient.encounters.unbilled.uniq %>  
      <% unless encounters.empty? %>  
        <div id="print_for_<%= patient.id %>">
          <div style="float:left;margin: 10px 0px 10px 30px;">
            <%= get_patient_name(patient)  %>  
            <b style="margin-left:20px;margin-right:10px;">DOB :</b><%= patient.date_of_birth.strftime("%Y/%m/%d")  %>  
          </div>  
          <table cellpadding="0" cellspacing="0" style="margin: 10px 0 10px 30px; width: 550px;">
            <tr class="interface_heading_print">
              <td class="col31_top none">DOS</td>
              <td class="none">ICD9(p)</td>
              <td class="none">ICD9</td>
              <td class="none">ICD9</td>
              <td class="none">ICD9</td>
              <td class="none">CPT</td>
            </tr>
            <% encounters.each do |encounter| %>  
              <%= hidden_field_tag "encounters[#{patient.id}][]", encounter.id  %>  
              <tr class="light_blue_print">
                <td class="col31"><%= encounter.date_of_service.strftime('%m/%d')  %></td>
                <% unless encounter.encounter_icds.primary.empty?  %> 
                  <td class="col31" style="text-align:center;"><%= encounter.encounter_icds.primary.first.icd.code %></td>   
                <% else  %>
                  <td class="col31" style="text-align:center;">&nbsp;</td> 
                <% end %>  
                <% general_icds = encounter.encounter_icds.general %> 
                <% unless general_icds[0].nil?  %> 
                  <td class="col31" style="text-align:center;"><%= general_icds[0].icd.code %></td> 
                <% else  %>
                  <td class="col31" style="text-align:center;">&nbsp;</td> 
                <% end %>  
                <% unless general_icds[1].nil?  %> 
                  <td class="col31" style="text-align:center;"><%= general_icds[1].icd.code %></td>   
                <% else %>
                  <td class="col31" style="text-align:center;">&nbsp;</td> 
                <% end %>  
                <% unless general_icds[2].nil?  %> 
                  <td class="col31" style="text-align:center;"><%= general_icds[2].icd.code %></td>   
                <% else %>
                  <td class="col31" style="text-align:center;">&nbsp;</td> 
                <% end %>  
                <td class="col31" style="text-align:center;"><%= get_cpts_codes(encounter.cpts.collect(&:cpt_id))  %></td>   
              </tr> 
            <% end %>  
          </table>
          <hr>
        </div>  
      <% end %>  
    <% end %>  
  </div>  
</div>
<script type="text/javascript">
  window.print();
  setTimeout(window.location = "<%= billing_agency_profile_path(@billing_agency.id)  %>", 1000);
</script>