config/routes.rb
CCWebApp::Application.routes.draw do

  # - Subscriptions -
  get "subscriptions/new"
  post "subscriptions/create_group"

  resources :orders

  devise_for :users, :controllers => {:sessions => "sessions", :confirmations => 'users', :passwords => "passwords"}
  resources :home

  match '/subscription' => 'subscribe#new', :as => 'subscription'

  resources :subscribe do
    get 'edit_billing_information'
    get 'providers'
    post 'providers'
    collection do
      get 'edit_billing_information'
      get 'billing_information'
      post 'create_billing_info'
      put 'update_billing_info'
      get 'checkout_confirmation'
    end
  end

  match 'reset_password/:id' => "admin/home#reset_password", :as => :reset_password
  match 'billing' => "activities#billing"
  namespace :admin do
    resources :home
  end

  resources :physician_groups, :path => 'groups' do
    post 'change_agency', :on => :collection
  end

  resources :physicians do
    get :photo
    get :change_billing_agency, :on => :collection
    post :upload
  end

  resources :providers


  resources :billing_agencies, :path => 'billing/agencies' do
    get 'profile'
    collection do
      get 'change_billing_agency'
      post 'search'
      post 'report'
      get 'history'
      post 'history'
      get 'physicians'
    end
  end

  resources :agency_employees, :path => 'agency/employees'

  resources :superbills do
    get :autocomplete_cpt_group_name, :on => :collection
    get :autocomplete_icd_description, :on => :collection
    get :autocomplete_cpt_code, :on => :collection
    get :add, :on => :collection
  end

  resources :referring_physicians, :path => 'referring/physicians'
  resources :facilities
  resources :activities do
    get :history, :on => :collection
  end
  resources :patients

  resources :capture_codes, :as => :encounters do
    get :autocomplete_icd_description, :on => :collection
    get :icd, :on => :collection
  end

  resources :notes

  resources :reports do
    get :autocomplete_physician_name, :on => :collection
    get :referral_volume,  :on => :collection
    post :referral_volume_report, :on => :collection
    get :list, :on => :collection
    post :generate, :on => :collection
  end

  match '/auth' => 'home#client_authentication', :as => 'http_auth', :method => :post
  match '/hm11' => 'home#index'
  match '/unsubscribe/:email' => 'home#unsubscribe'
  #match '/password' => 'home#forgot_password', :as => 'http_auth', :method => :post
  match '/pin' => 'home#set_pin', :as => 'http_auth', :method => :post

  match '/store_pin' => 'services#store_pin', :method => :post
  match '/forgot_pin' => 'services#forgot_pin', :method => :post
  match '/forgot_password' => 'services#forgot_password', :method => :post
  match '/superbill_pull' => 'services#superbill_pull', :method => :post

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'

  # - Searches -
  post '/search/npi' => 'searches#npi', :as => :npi_search

end

app/models/agency_employee.rb
class AgencyEmployee < ActiveRecord::Base
  set_table_name 'agency_employee'
  belongs_to :billing_agency, :class_name => 'BillingAgency', :foreign_key => :billing_agency_id
  has_many :billing_batches, :class_name => 'BillingBatch'
  has_one :user, :as => :resource, :dependent => :destroy
  has_many :billing_superbills, :through => :billing_agency, :source => :superbills

  accepts_nested_attributes_for :user, :allow_destroy => true
  validates :name, :presence => true
end

app/controllers/agency_employees_controller.rb
class AgencyEmployeesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :class => "AgencyEmployee"
  layout 'billing_agency' 
  
  def index
    @agency_employees = current_user.resource.agency_employees
     respond_to do |format|
       format.html # index.html.erb
     end
  end

  def show
  end

  def new
    @agency_employee = AgencyEmployee.new
    load_defaults
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def edit
    @agency_employee = AgencyEmployee.find(params[:id])
    @request_source = request.env["HTTP_REFERER"]
    respond_to do |format|
      format.html { render :layout => false if current_user.role?(ROLES[BILLING_ADMIN]) }
      
    end
  end

  def create
    @agency_employee = AgencyEmployee.new(params[:agency_employee])
    @agency_employee.user.roles = ROLES[BILLING_FUNCTIONAL].to_a
    @agency_employee.billing_agency_id = current_user.resource.id
    respond_to do |format|
      if @agency_employee.save
        flash[:notice] = 'Agency Employee was successfully created.'
        format.html { redirect_to(agency_employees_path) }  
        format.js {
          render :js => "window.location='#{agency_employees_path}'"
        }
      else 
        load_defaults
        format.html { render :action => "new" }
        format.js {
          render :partial => 'new'
        }
      end
    end
  end


  def update
    @request_source = request.env["HTTP_REFERER"]
    @agency_employee = AgencyEmployee.find(params[:id])
    @agency_employee.attributes = params[:agency_employee]
    respond_to do |format|
      if @agency_employee.save
        flash[:notice] = 'Agency Employee was successfully updated.'
        format.html { redirect_to(@request_source) }  
        format.js {
          render :js => "window.location='#{@request_source}'"
        }
      else 
        load_defaults
        format.html { render :action => "edit" }
        format.js {
          render :partial => 'new'
        }
      end
    end
  end


  def destroy
    @agency_employee = AgencyEmployee.find(params[:id])
    if @agency_employee.user.locked_at?
      @agency_employee.user.unlock_access!
    else
      @agency_employee.user.lock_access!
    end
    respond_to do |format|
      format.html { redirect_to(agency_employees_path) }
      format.js {
        render :js => "window.location='#{agency_employees_path}'"
      }

    end
  end

  def load_defaults
    @agency_employee.build_user if @agency_employee.user.nil?
  end

end

app/views/agency_employees/_form.html.erb
<script type="text/javascript">
  $(function() {
      initialize_form();

      var v = $("#frmAdmin").jcheck({notifiers: ["custom_errors"], live_notifiers: ["custom_errors"], field_prefix: "agency_employee"});
      v.validates("name", "user_attributes[email]",{presence: true});
      v.validates_format_of("user_attributes[email]", {"with": "email"});
      $('#frmAdmin').submit(function(e) {
        e.preventDefault();
        return v.is_valid();
        });
  });
</script>
<%= form_for(@agency_employee, :html => { :remote => true, :id => "frmAdmin" }, :builder => CCFormBuilder) do |f|  %>
  <fieldset>
    <%= f.text_field :name, :label => t('.name') + t('mandatory') %>
    <%= f.text_field :employee_number, :label => t('.number')  %>
    <%= f.text_field :address, :label => t('contact.address')  %>
    <%= label_tag t('contact.location')  %><br/>
    <%= text_field :agency_employee, :city, :class => "width1" %>
    <%= select :agency_employee, :state, STATES.collect{|s| [s.name, s.code]}, {:include_blank => "--select--"}, :class => "width2"%>
    <%= text_field :agency_employee, :zip, :class => "width3" %>
    <%= f.text_field :phone, :label => t('contact.phone')  %>
    <%= f.fields_for :user do |u|  %> 
      <%= u.text_field :email, :label => t('contact.email') + t('mandatory') %>
    <% end %>
    <div class="butons">
      <%= f.submit "Add", :class => :backgrnd %>
      <% if  current_user.role?(ROLES[BILLING_FUNCTIONAL])  %>
        <%= link_to 'Back', billing_agency_profile_path(current_user.resource), :class => "backgrnd_lnk margin_rte"  %> 
      <% else %>  
        <%= link_to 'Back', agency_employees_path, :class => "backgrnd_lnk margin_rte" %>
      <% end %>
      <%= image_tag "/images/spinner.gif", :id => "spinner", :style => "display:none;"  %>
    </div>
  </fieldset> 
<% end %>
<%= render :partial => "/physician_groups/events"  %>

app/views/agency_employees/_new.js.erb
$("#frmGroup").html('<%= escape_javascript(render :partial => "form") %>');

app/views/agency_employees/edit.html.erb
<%= stylesheet_link_tag 'jcheck'  %>  
<%= javascript_include_tag 'jcheck-0.7.1.min'  %>  
<% if current_user.role?(ROLES[BILLING_ADMIN]) %> 
  <div class="form_tab">
    <h1>Editing Agency Employee</h1>
    <div id="frmGroup">
      <%= render 'form' %>
    </div>
  </div>
<% elsif current_user.role?(ROLES[BILLING_FUNCTIONAL]) %> 
  <%= render :partial => '/layouts/agency_employee_left_menu'  %> 
  <div class="interface_right_section">
    <div class="form_tab">
      <h1>Editing Agency Employee</h1>
      <div id="frmGroup">
        <%= render 'form' %>
      </div>
    </div>
  </div>
<% end  %> 

app/views/agency_employees/index.html.erb
<%= render :partial => '/layouts/agency_admin_left_menu'  %>
<div class="interface_right_section">
  <h3>Employees</h3>
  <div class="add"><%= link_to "Add Employees", new_agency_employee_path, :rel => :facebox  %></div>
  <table cellpadding="0" cellspacing="0">
    <tr class="interface_heading">
      <td class="col31_top none">NAME</td>
      <td class="none">NUMBER</td>
      <td class="none">PHONE</td>
      <td class="none">EMAIL</td>
      <td class="none">&nbsp;</td>
    </tr>
    <% @agency_employees.each do |agency_employee|  %>
      <tr class="light_blue">
        <td class="col31"><%= agency_employee.name %> </td>
        <td><%= agency_employee.employee_number %> </td>
        <td><%= agency_employee.phone  %></td>
        <td><%= agency_employee.user.email  %></td>
        <td class="col32 border_right edit-link">
          <%= link_to "Edit", edit_agency_employee_path(agency_employee), :rel => "facebox" %>  |
          <% if agency_employee.user.locked_at?  %>
            <%= link_to "Enable", agency_employee_path(agency_employee), :method => :delete  %> 
          <% else %> 
            <%= link_to "Disable", agency_employee_path(agency_employee), :method => :delete  %> 
          <% end %> 
        </td>
      </tr>
    <% end %>  
  </table>
</div>

app/views/agency_employees/new.html.erb
<%= stylesheet_link_tag 'jcheck'  %>  
<%= javascript_include_tag 'jcheck-0.7.1.min'  %>  
<div class="form_tab">
  <h1>New Agency Employee</h1>

  <div id="frmGroup">
    <%= render 'form' %>
  </div>
</div>