config/routes.rb
CCWebApp::Application.routes.draw do

  # - Subscriptions -
  get "subscriptions/new"
  post "subscriptions/create_group"

  resources :orders

  devise_for :users, :controllers => {:sessions => "sessions", :confirmations => 'users', :passwords => "passwords"}
  resources :home

  match '/subscription' => 'subscribe#new', :as => 'subscription'

  resources :subscribe do
    get 'edit_billing_information'
    get 'providers'
    post 'providers'
    collection do
      get 'edit_billing_information'
      get 'billing_information'
      post 'create_billing_info'
      put 'update_billing_info'
      get 'checkout_confirmation'
    end
  end

  match 'reset_password/:id' => "admin/home#reset_password", :as => :reset_password
  match 'billing' => "activities#billing"
  namespace :admin do
    resources :home
  end

  resources :physician_groups, :path => 'groups' do
    post 'change_agency', :on => :collection
  end

  resources :physicians do
    get :photo
    get :change_billing_agency, :on => :collection
    post :upload
  end

  resources :providers


  resources :billing_agencies, :path => 'billing/agencies' do
    get 'profile'
    collection do
      get 'change_billing_agency'
      post 'search'
      post 'report'
      get 'history'
      post 'history'
      get 'physicians'
    end
  end

  resources :agency_employees, :path => 'agency/employees'

  resources :superbills do
    get :autocomplete_cpt_group_name, :on => :collection
    get :autocomplete_icd_description, :on => :collection
    get :autocomplete_cpt_code, :on => :collection
    get :add, :on => :collection
  end

  resources :referring_physicians, :path => 'referring/physicians'
  resources :facilities
  resources :activities do
    get :history, :on => :collection
  end
  resources :patients

  resources :capture_codes, :as => :encounters do
    get :autocomplete_icd_description, :on => :collection
    get :icd, :on => :collection
  end

  resources :notes

  resources :reports do
    get :autocomplete_physician_name, :on => :collection
    get :referral_volume,  :on => :collection
    post :referral_volume_report, :on => :collection
    get :list, :on => :collection
    post :generate, :on => :collection
  end

  match '/auth' => 'home#client_authentication', :as => 'http_auth', :method => :post
  match '/hm11' => 'home#index'
  match '/unsubscribe/:email' => 'home#unsubscribe'
  #match '/password' => 'home#forgot_password', :as => 'http_auth', :method => :post
  match '/pin' => 'home#set_pin', :as => 'http_auth', :method => :post

  match '/store_pin' => 'services#store_pin', :method => :post
  match '/forgot_pin' => 'services#forgot_pin', :method => :post
  match '/forgot_password' => 'services#forgot_password', :method => :post
  match '/superbill_pull' => 'services#superbill_pull', :method => :post

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'

  # - Searches -
  post '/search/npi' => 'searches#npi', :as => :npi_search

end

app/models/report.rb
class Report < ActiveRecord::Base
  def self.columns() @columns ||= []; end
  def self.column(name, sql_type = nil, default = nil, null = true)
    columns << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, sql_type.to_s, null)
  end

  attr_accessor :activity_log

  column :physician_id, :integer
  column :referring_physician_id, :integer
  column :start_date, :date
  column :end_date, :date

  validates :physician_id, :presence => true, :unless => :is_active_log? 
  validates :start_date, :presence => true
  validates :end_date, :presence => true

  def is_active_log?
    self.activity_log.blank? 
  end
end

class BillingPatient < ActiveRecord::Base
  def self.columns() @columns ||= []; end
  def self.column(name, sql_type = nil, default = nil, null = true)
    columns << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, sql_type.to_s, null)
  end

  column :physician, :integer
  column :group, :integer
end

app/controllers/reports_controller.rb
require 'pdf_report'
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource 
  layout 'physician'
  autocomplete :physician, :name

  def index
    @report = Report.new
    @patients = []
    load_physicians
    respond_to do |format| 
      format.html
    end
  end

  def create
    @report = Report.new(params[:report])  
    load_physicians
    @report.activity_log = true 
    unless @report.valid? # show error
      @patients = []
      physician = current_user.resource
      respond_to do |format| 
        format.html {    render :action => 'index' }
      end
    else
      physician = Physician.find(@report.physician_id)
      @patients = physician.patients
      get_hash(@report.start_date, @report.end_date)
      unless @hash.empty?      
        if params[:commit_id] == "html"  # generate html report
          respond_to do |format| 
            format.html {    render :action => 'index' }
          end
        elsif params[:commit_id] == "pdf" # generate pdf report
          pdf =  PdfReport.generate_activity_log_report(physician, @patients, @hash, @report.start_date, @report.end_date)  
          send_data(pdf.render ,:type => 'application/pdf', :filename => "actvity_log_report-#{Date.today.strftime("%Y-%m-%d")}.pdf", :disposition=> "attachment")
        elsif params[:commit_id] == "excel" # generate csv report
          csv_string = CsvReport.generate_activity_log_report(physician, @patients, @hash, @report.start_date, @report.end_date) 
          filename = "activity_log_report.csv" 
          send_data(csv_string, :type => 'text/csv; charset=utf-8; header=present', :filename => filename)
        end
      else
        flash[:notice] = 'No data available.'
        respond_to do |format| 
          format.html {    render :action => 'index' }
        end
      end
    end
  end

  def referral_volume
    @report = Report.new
    get_referring_physicians
    respond_to do |format| 
      format.html 
    end

  end

  def referral_volume_report
    @report = Report.new(params[:report])
    @records = nil
    get_referring_physicians
    if @report.valid?
      if @report.referring_physician_id.blank? 
        id = @referring_physicians.collect(&:id)
      else
        referring_physician =  ReferringPhysician.find(@report.referring_physician_id)
        id = referring_physician.id.to_a
      end
      get_referal_volume(id, @report.start_date, @report.end_date)
      if  @records.first.nil?
        flash[:notice] = 'No data available.'
        @records = nil
        respond_to do |format| 
          format.html { render :action => 'referral_volume' } 
        end
      else
        if params[:commit_id] == "html"
          respond_to do |format| 
            format.html { render :action => 'referral_volume' } 
          end
        elsif params[:commit_id] == "pdf"
          pdf =  PdfReport.generate_referral_volume_report(@records, @flag, @report.start_date, @report.end_date)
          send_data(pdf.render ,:type => 'application/pdf', :filename =>  "referral_volume_report.pdf", :disposition=> "attachment")
        elsif params[:commit_id] == "excel"
          records = @records   
          flag = @flag
          csv_string = CsvReport.generate_referral_volume_report(records, flag) 
          filename = "referral_volume_report.csv" 
          send_data(csv_string, :type => 'text/csv; charset=utf-8; header=present', :filename => filename)
        end
      end  
    else
      respond_to do |format| 
        format.html { render :action => 'referral_volume' } 
      end
    end
  end


  def get_referring_physicians
    unless current_user.resource.group_id.nil?
      @referring_physicians = current_user.resource.referring_physicians.private | current_user.resource.physician_group.referral_physicians.visible
    else
      @referring_physicians = current_user.resource.referring_physicians
    end
  end

  def get_referal_volume(physician_id, start_date, end_date)
    end_date = end_date.to_s.gsub('/', '-')
    start_date = start_date.to_s.gsub('/', '-') 
    @flag = 0 #to show all records
    @records =  HospitalEpisode.referral_volume(physician_id, start_date, end_date)
    unless  @report.referring_physician_id.blank? 
      @flag = 1 # to show specific record
      @records = @records.select{ |a| a.rid == @report.referring_physician_id }
    end 
  end

  def list
    @report = Report.new
    @result = {} 
    load_physicians
  end

  def generate
    load_physicians
    @report = Report.new(params[:report])
    @result = ActiveSupport::OrderedHash.new
    if @report.valid?
      physicians = @report.physician_id.blank? ? @physicians.collect(&:id) : @report.physician_id.to_a
      encounters = Encounter.monthly_encounters(physicians, @report.start_date, @report.end_date)
      patients = Patient.monthly_patients(physicians, @report.start_date, @report.end_date)
      patients.each do |patient|
        @result[Date::MONTHNAMES[patient.month.to_i]] = get_avg_stay(patient, encounters) 
      end 
      if @result.empty?
        flash[:notice] = "No data available"
        respond_to do |format|
          format.html { render :action => 'list'}
        end
      else
        if params[:commit_id] == "html"
          respond_to do |format|
            format.html { render :action => 'list'}
          end
        elsif params[:commit_id] == "pdf"
          pdf =  PdfReport.generate_average_length_of_stay_report(@result, @report.start_date, @report.end_date)
          send_data(pdf.render ,:type => 'application/pdf', :filename =>  "average_length_of_stay_report.pdf", :disposition=> "attachment")
        elsif params[:commit_id] == "excel"
          result = @result   
          csv_string = CsvReport.generate_average_length_of_stay_report(result) 
          filename = "average_length_of_stay_report.csv" 
          send_data(csv_string, :type => 'text/csv; charset=utf-8; header=present', :filename => filename)
        end
      end
    else
      respond_to do |format|
        format.html { render :action => 'list'}
      end
    end
  end


  def load_physicians
    @physicians = current_user.resource.group_id.nil? ?  current_user.resource.to_a : current_user.resource.physician_group.physicians
  end


  def autocomplete_physician_name
    term = params[:term]
    if term && !term.empty?
      unless current_user.resource.group_id.nil?
        items = Physician.where(["LOWER(name) LIKE ? and group_id = ?", "%#{term.downcase}%",  current_user.resource.group_id]) \
          .limit(10).order("name ASC")
      else
        items = Physician.where(["LOWER(name) LIKE ? and physician_id = ?", "%#{term.downcase}%",  current_user.resource.id]) \
          .limit(10).order("name ASC")
      end
    else
      items = {}
    end
    render :json => json_for_autocomplete(items, :name)
  end



  def get_hash(start_date, end_date)
    @hash = Hash.new
    @patients.each do |patient|
      patient.encounters.each do |encounter|
        if !encounter.cpts.empty? or !encounter.encounter_icds.empty? 
          if encounter.date_of_service >= start_date and  encounter.date_of_service <= end_date  
            @hash = @hash.merge( patient.id => {} ) unless @hash[patient.id]
            @hash[patient.id] =@hash[patient.id].merge(encounter.date_of_service.strftime("%Y/%m/%d") => {} )
            encounter.cpts.each do |cpts|
              @hash[patient.id][encounter.date_of_service.strftime("%Y/%m/%d")] =  @hash[patient.id][encounter.date_of_service.strftime("%Y/%m/%d")].merge( cpts.cpt_id => {:code => cpts.cpt.code, :description => cpts.cpt.description  } )
            end
            encounter.encounter_icds.each do |icds|
              @hash[patient.id][encounter.date_of_service.strftime("%Y/%m/%d")] =  @hash[patient.id][encounter.date_of_service.strftime("%Y/%m/%d")].merge( icds.icd_id => { :code => icds.icd.code, :description => icds.icd.description  } )
            end
          end
        end
      end
    end 
  end

  def get_avg_stay(patient, encounters)
    encounter = encounters.select{|a| a.month == patient.month}
    encounter.empty? ? "0" : (encounter.first.counts.to_i/ patient.counts.to_i)
  end

end

app/views/reports/_create.js.erb
$("#patient_info").html('<%= escape_javascript(render :partial => "form") %>');
$("#physician_error").html("<div class='errMsg'><%= @report.errors[:error_physician_id].first %></div>" );  

app/views/reports/_form.html.erb
<table cellpadding="0" cellspacing="0">
  <tr class="interface_heading">
    <td class="col1 none">PATIENT NAME</td>
    <td class="col1 none">DOB</td>
    <td class="col1 none">EMAIL</td>
    <td class="col1 none">DATE</td>
    <td class="col1 none">CODE</td>
    <td class="col1 none">DESCRIPTION</td>
  </tr>
  <% @patients.each do |patient|  %>
    <% if @hash[patient.id] %> 
      <tr class="light_blue">
        <td class="col11">
          <%= get_patient_name(patient) %>
        </td>
        <td> <%= patient.date_of_birth  %> </td>
        <% unless patient.email.blank?  %> 
          <td> <%= patient.email  %> </td>
        <% else %> 
          <td>&nbsp;</td>
        <% end %>
        <% cnt1=0 %> 
        <% @hash[patient.id].each do |date , id| %> 
          <% if cnt1==0  %> 
            <td><%= date  %></td>
          <% else %> 
            <tr class="col11"> <td class="col11">&nbsp;</td><td class="light_blue">&nbsp;</td><td class="light_blue">&nbsp;</td><td class="light_blue"><%= date  %></td>
          <% end %>
          <% cnt1+=1 %> 
          <% cnt2=0 %> 
          <% @hash[patient.id][date].each do |id, val| %> 
            <% if cnt2==0  %> 
              <td class="light_blue"><%= @hash[patient.id][date][id][:code] %></td>   
              <td class="light_blue"><%= @hash[patient.id][date][id][:description] %></td>   
            <% else %> 
              <tr class="light_blue"><td class="col11">&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                <td><%= @hash[patient.id][date][id][:code] %></td>   
                <td><%= @hash[patient.id][date][id][:description] %></td>   
              </tr>
            <% end %> 
            <% cnt2+=1 %> 
          <% end %> 
        <% end %> 
        <%if @hash[patient.id].empty? %> 
          <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        <% end %>
      </tr> 
    <% end  %>   
  <% end  %>   
</table>

app/views/reports/_menu.html.erb
<div class="left_navigation">
  <ul>
    <li><%= menu_link_to 'reports', '[index, create]', 'Activity Log', reports_path %></li>
    <li><%= menu_link_to 'reports', '[list, generate]', "Average Length of stay", list_reports_path  %>  </li>
    <li><%= menu_link_to 'reports', '[referral_volume, referral_volume_report]', 'Referral Volume',  referral_volume_reports_path %></li>
  </ul>
</div>

app/views/reports/_referral_report.html.erb
<table cellpadding="0" cellspacing="0">
  <tr class="interface_heading">
    <td class="col1 none">Physician</td>
    <td class="col1 none">Month</td>
    <td class="col1 none">Referral Count</td>
  </tr>
  <% if @flag == 1  %> 
    <%  cnt = 0  %> 
    <tr class="light_blue">
      <td class="col11"><%= @records.first.name %></td> 
      <% @records.each do |r| %> 
        <% if cnt == 0  %>  
          <td class="light_blue"><%= Date::ABBR_MONTHNAMES[r.month.to_i] %></td>
          <td><%= r.ref_count %></td>
          <%  cnt = cnt + 1  %> 
        <% elsif cnt != 0  %>  
          <td class="col11"></td> 
          <td class="light_blue"><%= Date::ABBR_MONTHNAMES[r.month.to_i] %></td>
          <td class="light_blue"><%= r.ref_count %></td>
        <% end %> 
      </tr>
    <% end %> 
  <% else %> 
    <% @records.each do |r| %> 
      <tr class="light_blue">
        <td class="col11"><%= r.name %></td> 
        <td class="light_blue"><%= Date::ABBR_MONTHNAMES[r.month.to_i] %></td>
        <td><%= r.ref_count %></td>
      </tr>
    <% end %> 
  <% end %> 
</table>  

app/views/reports/index.html.erb
<script type="text/javascript">
  function submit_form(id)
{
  $('#commit_id').val(id);
  $('#frmAdmin').submit();
}
</script>

<%= render :partial => "/layouts/notice"  %>
<div id="page">
  <div class="interface_left_section">
    <%= render :partial => 'menu'  %>
    <%= render :partial => '/layouts/physician_profile'  %>
  </div>
  <div class="interface_right_section">
    <h3 class="pad_btm">Reports/Activity Log</h3>
    <%= render :partial => "/layouts/physician_header"  %>
      <%= form_for(@report, :html => { :id => "frmAdmin" }) do |f| %>
        <fieldset>
          <div> 
            <div class="fields">
              <%= raw f.label t('.physician') + t('mandatory') %>  
              <%= f.select :physician_id, @physicians.collect{|p| [p.name, p.id]}, {:include_blank => "--select--"} %>  
              <%= raw "<br/><div class='physician_error'>#{@report.errors[:physician_id].first}</div>" unless @report.errors[:physician_id].empty? %>  
            </div>  
            <%#= select_tag :superbill, options_from_collection_for_select(@superbills, 'id', 'name', @preferred_superbill.to_s) , :include_blank => '--select--' ,:style => "width:290px;" %>
            <%#= select_tag :physician_id, options_from_collection_for_select(@physicians, 'id', 'name' ), :include_blank => "--select--", :style => "width:200px;" %>  
            <%#= autocomplete_field_tag "physician_name", '',autocomplete_physician_name_reports_path, :size => 15, :id_element => '#physician_id' %>
            <%#= hidden_field_tag "physician_id", @report.physician_id.to_s  %>
            <%= hidden_field_tag "commit_id", ""  %>
            <div style="float:left;">
              <%= label_tag t('.start_date') + t('mandatory') %>
              <%= raw f.date_select :start_date %>
              <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:start_date].first}</div>" unless @report.errors[:start_date].empty?  %> 
            </div>
            <div style="float:right;">
              <%= f.label t('.end_date') + t('mandatory'), :class => "apd_left"%>
              <%= raw f.date_select :end_date %>
              <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:end_date].first}</div>" unless @report.errors[:end_date].empty?  %> 
            </div>
          </div>
        </fieldset>
      <% end  %>   
    <div class="nav_right">
      <div class="add"><%= link_to_function 'Generate Report', "submit_form('html')", :id => "generate_report" %> </div>
      <div class="add"><%= link_to_function 'Export to PDF', "submit_form('pdf')", :id => "export_pdf" %> </div>
      <div class="add"><%= link_to_function 'Export to Excel', "submit_form('excel')", :id => "export_excel" %> </div>
    </div>
    <% if @hash  %> 
      <% unless @hash.empty? %> 
        <div id="patient_info">
          <%= render :partial => "form"  %>  
        </div>  
      <% end %> 
    <% end %> 
  </div>
</div>

app/views/reports/list.html.erb
<script type="text/javascript">
  function submit_form(id)
{
  $('#commit_id').val(id);
  $('#frmAdmin').submit();
}
</script>

<%= render :partial => "/layouts/notice"  %>
<div id="page">
  <div class="interface_left_section">
    <%= render :partial => 'menu'  %>
    <%= render :partial => '/layouts/physician_profile'  %>
  </div>
  <div class="interface_right_section">
    <h3 class="pad_btm">Average Length of Stay</h3>
    <%= render :partial => "/layouts/physician_header"  %>
    <%= form_for(@report, :url => generate_reports_path, :html => { :id => "frmAdmin" }) do |f| %>
      <fieldset>
        <div>
          <div class="fields">
            <%= raw f.label t('reports.index.physician')  %>  
            <%= f.select :physician_id, @physicians.collect{|p| [p.name, p.id]}, {:include_blank => "All"} %>  
          </div>  
          <%= hidden_field_tag "commit_id", ""  %>
          <div id="physician_error">
            <%= raw "<div class='errMsg_short'>#{@report.errors[:physician_id].first}</div>" unless @report.errors[:physician_id].empty? %>  
          </div>
          <br />
          <div style="float:left;">
            <%= label_tag t('reports.index.start_date') + t('mandatory') %>
            <%= raw f.date_select :start_date %>
            <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:start_date].first}</div>" unless @report.errors[:start_date].empty?  %> 
          </div>
          <div style="float:right;">
            <%= f.label t('reports.index.end_date') + t('mandatory'), :class => "apd_left"%>
            <%= raw f.date_select :end_date %>
            <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:end_date].first}</div>" unless @report.errors[:end_date].empty?  %> 
          </div>
        </div>
      </fieldset>
    <% end  %>   
    <div class="nav_right">
      <div class="add"><%= link_to_function 'Generate Report', "submit_form('html')", :id => "generate_report" %> </div>
      <div class="add"><%= link_to_function 'Export to PDF', "submit_form('pdf')", :id => "export_pdf" %> </div>
      <div class="add"><%= link_to_function 'Export to Excel', "submit_form('excel')", :id => "export_excel", :format => :csv %> </div>
    </div>
    <% unless params[:action] == "list" %>  
      <% if @result.empty? %>  
        <div style="float:left;width:100%;margin-top:30px;">
          <%= flash[:notice]  %>  
        </div>
      <% else %>  
        <div style="float:left;width:100%;margin-top:30px;">
          <div style="width:50%;float:left;">
            <table>
              <tr class="interface_heading">
                <td class="col1 none">Month</td>
                <td class="col1 none">Average Length of stay</td> 
              </tr> 
              <% @result.each do |key, val| %>  
                <tr class="light_blue">
                  <td><%= key  %></td>   
                  <td><%= val  %> days</td>   
                </tr> 
              <% end %>  
            </table>  
          </div>  
          <div style="width:50%;float:left;">
            <div style="float:left;margin-left;20px;">
              <%= image_tag(Gchart.line(:title => 'Avg length of stay', :data => @result.values, :axis_with_labels => 'x,y', :axis_labels => [@result.keys.join('|'), "0|" + @result.values.sort.join('|')]))  %>  
            </div>  
          </div>  
        </div>  
      <% end %>  
    <% end %>  
  </div>
</div>

app/views/reports/referral_volume.html.erb
<script type="text/javascript">
  function submit_form(id)
{
  $('#commit_id').val(id);
  $('#frmAdmin').submit();
}
</script>


<%= render :partial => "/layouts/notice"  %>
<div id="page">
  <div class="interface_left_section">
    <%= render :partial => 'menu'  %>
    <%= render :partial => '/layouts/physician_profile'  %>
  </div>
  <div class="interface_right_section">
    <h3 class="pad_btm">Reports/Referral Volume</h3>
    <%= render :partial => "/layouts/physician_header"  %>
    <%= form_for(@report, :html => {:id => "frmAdmin" }, :url => referral_volume_report_reports_path) do |f| %>
      <fieldset>
        <div>
          <div class="fields">
            <%= label_tag  t('.referring_physician')  %>  
            <%= f.select :referring_physician_id, @referring_physicians.collect{|p| [p.name, p.id]}, {:include_blank => "All"} %>  
          </div>  
          <%= hidden_field_tag "commit_id", ""  %>
          <br />
          <div style="float:left;">
            <%= label_tag t('.start_date') + t('mandatory') %>
            <%= raw f.date_select :start_date %>
            <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:start_date].first}</div>" unless @report.errors[:start_date].empty?  %> 
          </div>
          <div style="float:right;">
            <%= f.label t('.end_date') + t('mandatory'), :class => "apd_left"%>
            <%= raw f.date_select :end_date %>
            <%= raw "<br/><div class='errMsg_short'>#{@report.errors[:end_date].first}</div>" unless @report.errors[:end_date].empty?  %> 
          </div>
        </div>
      </fieldset>
    <% end  %>   
    <div class="nav_right">
      <div class="add"><%= link_to_function 'Generate Report', "submit_form('html')", :id => "generate_report" %> </div>
      <div class="add"><%= link_to_function 'Export to PDF', "submit_form('pdf')", :id => "export_pdf" %> </div>
      <div class="add"><%= link_to_function 'Export to Excel', "submit_form('excel')", :id => "export_excel" %> </div>
    </div>
    <% if @records  %> 
      <div id="patient_info">
        <%= render :partial => "referral_report"  %>  
      </div>  
    <% end  %>   
  </div>
</div>